branches:
  - main
plugins:
  - "@semantic-release/release-notes-generator"
  - - semantic-release-gitmoji
    - releaseRules:
        major:
          - ":boom:"
        minor:
          - ":sparkles:"
        patch:
          - ":bug:"
          - ":ambulance:"
          - ":lock:"
          - ":arrow_up:"
          - ":adhesive_bandage:"
  - - "@semantic-release/gitlab"
    - useJobToken: true
      assets:
        - path: dist/pypi/*
          label: PyPI distribution
