services:
  web-gui:
    build: .
    command: "uv run vtr serve-streamlit"
    volumes:
      - app-data:/app/data
    restart: unless-stopped
    depends_on:
      - db

  rest-api:
    build: .
    command: "uv run vtr serve-fastapi-prod"
    environment:
      - APP_DB_HOST=db
      - APP_DB_USER=app
      - APP_DB_DATABASE=app
      - SERVICE_PASSWORD_DB
    volumes:
      - app-data:/app/data
    restart: unless-stopped
    depends_on:
      - db

  docs:
    build: .
    command: "uv run vtr serve-docs-prod"
    environment:
      SITE_URL: "${SERVICE_URL_APP}/docs"
    restart: unless-stopped

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "${SERVICE_PASSWORD_DB}"
    volumes:
      - db-data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  app-data: {}
  db-data: {}
