services:
  web-gui:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: vtr
      args:
        DEPS_GROUP: web-gui
    command: serve-streamlit
    volumes:
      - app-data:/app/data
    restart: unless-stopped
    depends_on:
      - db

  rest-api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: vtr
      args:
        DEPS_GROUP: rest-api
    command: serve-fastapi-prod
    environment:
      APP_DB_URL: "postgresql://app:${SERVICE_PASSWORD_DB}@db/app"
    volumes:
      - app-data:/app/data
    restart: unless-stopped
    depends_on:
      - db

  docs:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: nginx-docs
      args:
        DEPS_GROUP: docs
        SITE_URL: "${SERVICE_URL_DOCS}/docs"
    restart: unless-stopped

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "${SERVICE_PASSWORD_DB}"
    volumes:
      - db-data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  app-data: {}
  db-data: {}
