name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:alpine

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore uv virtualenv cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-cache-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            venv-cache-${{ runner.os }}-

      - name: Install dependencies
        run: uv sync --group dev --group ci

      - name: Build package
        run: uv build --out-dir ./dist/pypi

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv run semantic-release publish
